[build]
  command = "npm run build:netlify"
  publish = "dist"

[build.environment]
  # Use correct NPM flags for CI environment
  NPM_FLAGS = "--include=dev --legacy-peer-deps"
  NODE_ENV = "production"
  NODE_OPTIONS = "--max-old-space-size=4096"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ensure proper caching for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
