[build]
  publish = "static-build"
  command = "bash -c 'chmod +x build-netlify.sh && ./build-netlify.sh'"

# Configure redirects for Single Page Application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
