[build]
  command = "npm run build:netlify"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ensure proper caching for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
