name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git user
      run: |
        git config --global user.name "Devalo1"
        git config --global user.email "dani_popa21@yahoo.ro"

    - name: Install dependencies
      run: npm install

    - name: Run pre-build cleanup
      run: npm run clean-config

    - name: Build project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
