name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SHARP_IGNORE_GLOBAL_LIBVIPS: "1"
      npm_config_arch: x64
      npm_config_platform: linux

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Sharp dependencies
      run: sudo apt-get update && sudo apt-get install -y libvips-dev

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: |
        npm install --no-optional
      env:
        SHARP_DIST_BASE_URL: "https://npmmirror.com/mirrors/sharp-libvips"

    - name: Build project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true
