name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Create placeholder images
      run: |
        mkdir -p public/images
        echo '<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080"><rect width="100%" height="100%" fill="#8b5a2b"/><text x="50%" y="50%" font-family="Arial" font-size="72" text-anchor="middle" fill="white">Lupul si Corbul</text></svg>' > public/images/cover.svg
        echo '<svg xmlns="http://www.w3.org/2000/svg" width="300" height="100"><rect width="100%" height="100%" fill="#fff8f0" rx="10" ry="10"/><text x="50%" y="60%" font-family="Arial" font-size="32" font-weight="bold" text-anchor="middle" fill="#6b4423">Lupul si Corbul</text></svg>' > public/images/Logo.svg
        cp public/images/cover.svg public/images/cover.jpeg
        cp public/images/Logo.svg public/images/Logo.png

    - name: Debug environment
      run: |
        echo "Node version: $(node -v)"
        echo "NPM version: $(npm -v)"
        echo "Current directory: $(pwd)"
        echo "Directory contents: $(ls -la)"

    - name: Build directly with Vite
      run: |
        npm install vite --no-save
        npx vite build --base=/my-website/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true
