name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create dist directory with static site
      run: |
        mkdir -p dist
        mkdir -p dist/images
        
        # Create index.html with redirect
        cat > dist/index.html << 'EOL'
        <!DOCTYPE html>
        <html lang="ro">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Lupul și Corbul</title>
          <style>
            body { 
              font-family: Arial, sans-serif; 
              background-color: #fff8f0; 
              text-align: center; 
              padding: 50px; 
            }
            .card {
              background-color: white;
              border-radius: 10px;
              padding: 30px;
              box-shadow: 0 4px 8px rgba(0,0,0,0.1);
              max-width: 600px;
              margin: 0 auto;
            }
            h1 { color: #6b4423; }
            .message { margin: 20px 0; }
            .link {
              display: inline-block;
              margin-top: 20px;
              background-color: #8b5a2b;
              color: white;
              padding: 10px 20px;
              text-decoration: none;
              border-radius: 5px;
            }
          </style>
        </head>
        <body>
          <div class="card">
            <h1>Lupul și Corbul</h1>
            <div class="message">
              <p>Site-ul este în construcție și va fi disponibil în curând.</p>
              <p>Vă mulțumim pentru răbdare!</p>
            </div>
            <a class="link" href="https://github.com/Devalo1/my-website">Vezi proiectul pe GitHub</a>
          </div>
        </body>
        </html>
        EOL
        
        # Create a placeholder image
        cat > dist/images/placeholder.svg << 'EOL'
        <svg xmlns="http://www.w3.org/2000/svg" width="300" height="100">
          <rect width="100%" height="100%" fill="#fff8f0" rx="10" ry="10"/>
          <text x="50%" y="60%" font-family="Arial" font-size="24" font-weight="bold" text-anchor="middle" fill="#6b4423">Lupul si Corbul</text>
        </svg>
        EOL
        
        echo "Static site created successfully"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true
