name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install CI dependencies
      run: |
        # Skip installing Sharp during CI build
        npm ci --no-optional --omit=dev || npm install --no-optional --omit=dev

    - name: Create placeholder images
      run: |
        mkdir -p public/images
        # Create basic SVG images instead of using Sharp
        echo '<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080"><rect width="100%" height="100%" fill="#8b5a2b"/><text x="50%" y="50%" font-family="Arial" font-size="72" text-anchor="middle" fill="white">Lupul si Corbul</text></svg>' > public/images/cover.svg
        echo '<svg xmlns="http://www.w3.org/2000/svg" width="300" height="100"><rect width="100%" height="100%" fill="#fff8f0" rx="10" ry="10"/><text x="50%" y="60%" font-family="Arial" font-size="32" font-weight="bold" text-anchor="middle" fill="#6b4423">Lupul si Corbul</text></svg>' > public/images/Logo.svg
        echo 'Files created to skip Sharp dependency'

    - name: Build project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true
